import type { Metadata } from "next";
import { ReactNode } from "react";
import { ShopApp, ShopCategoryDescriptionApp } from "@/components/module/Shop/Shop";
import { ShopMain } from "@/components/module/Shop/ShopMain";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ShopLayout({children}: Readonly<{children: ReactNode}>) {
    return (
        <ShopMain>
            <ShopMain.Header>
                {children}
            </ShopMain.Header>
            <ShopMain.Footer>
                <ShopCategoryDescriptionApp/>
            </ShopMain.Footer>
        </ShopMain>
    )
}
